### ISSUE TITLE
Graphic issue after screen rotation 

### ISSUE THREAD

**Issue by TDalBet** [openopus-org/concertino_ios#7]
Hello! Bom dia , Adriano!

I have another small issue to report

iPhone XS Max, iOS 10.5.1

How to reproduce it:
1. Start a radio
2. Rotate the device in landscape
3. Rotate the device again in portrait
4. The upper part of the screen is cut and Track names are… One on another. See screenshot. 

This thing occurs always, so you will be able to reproduce the issue. 

![6D490F49-8604-41D9-9DC0-2A2D8DAF33AA](https://user-images.githubusercontent.com/67911294/86766322-ae251480-c04a-11ea-83ab-c0d3ba275ead.png)

Bye.

**Comment by adrianosbr** [comment]
Hi! Thanks for pointing that out! Just fixed it for our next release :)

**Comment by TDalBet** [comment]
Obrigado, Adriano!
